### ISSUE TITLE
localized keyboard layouts

### ISSUE THREAD

**Issue by anoff** [JunSuzukiJapan/atom-keyboard-macros#10]
I am under the impression that the plugin has issues with local keyboard layouts. Tried recording a macro on a german keyboard layout using quotes `"` which caused the macro to create `@` during replay.
Haven't investigated the code yet but german layout has `"` on shift+2, which is where the `@` is located on US layouts.
Any ideas how to fix this?

**Comment by g200kg** [comment]
Same problem on japanese localized keyboard. (Win10)

It can work if modify the WindowsAndLinuxCharCodeTranslations table appropriatly.
Even it is not good solution, (and maybe for Windows and Linux only)

Additionally, in japanese keyboard, the hotkeys 'ctrl-x (' and 'ctrl-x )' also deviated to US keyboard position. This may be a problem of Atom itself.

**Comment by pgibelin** [comment]
I am having the same issue on a system with a Spanish (ES) keyboard under Windows 10. 

Whenever I press **[ctrl]-x (**, all I get is the opening and closing brackets with the cursor in between, as if I hadn't typed **[ctrl]-x** before it.

I am new to atom, so the issue could be that I didn't configure the package correctly or that I somehow mistype the sequence, but it does seem to be enabled as the key binding resolver does show that Ctrl-x is for this atom-keyboard-macros.

Any hints?

**Comment by anoff** [comment]
as I don't use Atom anymore and noone seems to care I'll close this issue and leave it open for someone else to keep tracking this
