### ISSUE TITLE
Doesn't record space

### ISSUE THREAD

**Issue by 7underlines** [JunSuzukiJapan/atom-keyboard-macros#2]
I had this data
12
99
12
97

And I wanted it to look like this
12 99
12 97

But it always came out like this
1299
1297

**Comment by JunSuzukiJapan** [comment]
I'm confirmed the problem.

**Comment by JunSuzukiJapan** [comment]
I fixed it.

I divided the processing of the space and the other key,　try version 0.1.1. please.

**Comment by 7underlines** [comment]
Thx, it really works now, you are amazing fast! :)
