### ISSUE TITLE
Tab and " with french keyboard not working

### ISSUE THREAD

**Issue by snkkid99** [JunSuzukiJapan/atom-keyboard-macros#3]
Hi

for example I start with that:
1
2
3

I record a macro that transform the 1st line in that:
<hard tab>"1"

and the result with macro execution on next line is :
323
333

version used 0.8.0

Thanks

**Comment by JunSuzukiJapan** [comment]
I fixed about hard tab, maybe.

But I don't know about french keyboard, so don't fix about ".
Do you know key code of " in french keyboard?

**Comment by snkkid99** [comment]
Thanks for your update the hard tab and the " work.

this is weird because you say that you haven't do anything with the ".
