### ISSUE TITLE
Macro incorrectly records ")" key

### ISSUE THREAD

**Issue by haberdashPI** [JunSuzukiJapan/atom-keyboard-macros#34]
Although ")" is a part of the keyboard command for closing a macro, it gets recorded as part of hte macro.

E.g. executing a macro which adds "bob" to the end of a line results in this if I repeat the macro

```
some lines of text
are written here as an example
```

turns into

```
some lines of text "bob"
) are written here as an example "bob
)
```

The expected result would be

```
some lines of text "bob"
are written here as an example "bob"
```

**Comment by mbolivar** [comment]
dupe: https://github.com/JunSuzukiJapan/atom-keyboard-macros/issues/16
