### ISSUE TITLE
Unable to dismiss the information bar

### ISSUE THREAD

**Issue by shouya** [JunSuzukiJapan/atom-keyboard-macros#7]
There is currently no way to dismiss this information bar created by `atom-keyboard-macros`. Adding an action to dismiss it would be good. Or it should disappear automatically after a period of inactivity.

<img width="241" alt="screen shot 2016-03-10 at 6 43 12 am" src="https://cloud.githubusercontent.com/assets/526598/13669788/61d0784c-e68b-11e5-8f14-4282390dd638.png">

**Comment by JunSuzukiJapan** [comment]
'atom-keyboard-macros:toggle' command toggle the window.
Also it use from menu bar, or context menu.

Is this useful for you?

**Comment by shouya** [comment]
Thanks for the information. I tried `atom-keyboard-macros:toggle` but it seems not doing anything.

**Comment by JunSuzukiJapan** [comment]
When the information bar is displayed, using the command does not disappear the bar?

**Comment by shouya** [comment]
It works to me now (with a clean startup). Thanks.
