### ISSUE TITLE
Enter key no longer works in find text box.

### ISSUE THREAD

**Issue by chips5ahoy** [JunSuzukiJapan/atom-keyboard-macros#9]
After executing a macro the enter key no longer finds the next match when pressed in the find window.

**Comment by JunSuzukiJapan** [comment]
I fixed it, maybe.
Try v0.9.0, please.

thanks.

**Comment by chips5ahoy** [comment]
Thank you!  :)

I will check it out on Monday.

**Comment by chips5ahoy** [comment]
It works beautifully!  Thank you.
